Voat/Voat.UI/Controllers/PartnerController.cs
/*
This source file is subject to version 3 of the GPL license, 
that is bundled with this package in the file LICENSE, and is 
available online at http://www.gnu.org/licenses/gpl.txt; 
you may not use this file except in compliance with the License. 

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
the specific language governing rights and limitations under the License.

All portions of the code written by Voat are Copyright (c) 2015 Voat, Inc.
All Rights Reserved.
*/

using System;
using System.Net.Mail;
using System.Text;
using System.Web.Mvc;
using Voat.Models;
using Voat.UI.Utilities;
using Voat.Utilities;

namespace Voat.Controllers
{
    public class PartnerController : Controller
    {
        // GET: PartnerIntentRegistration
        public ActionResult PartnerProgramInformation()
        {
            return View();
        }

        // GET: PartnerIntentRegistration
        [RequireHttps]
        [Authorize]
        public ActionResult PartnerIntentRegistration()
        {
            var model = new PartnerIntent {UserName = User.Identity.Name};
            return View(model);
        }

        [Authorize]
        [RequireHttps]
        [HttpPost]
        [PreventSpam(DelayRequest = 300, ErrorMessage = "Sorry, you are doing that too fast. Please try again later.")]
        [ValidateCaptcha]
        public ActionResult PartnerIntentRegistration(PartnerIntent partnerModel)
        {
            if (!ModelState.IsValid) return View();

            var from = new MailAddress(partnerModel.Email);
            var to = new MailAddress("legal@voat.co");
            var sb = new StringBuilder();
            var msg = new MailMessage(@from, to)
            {
                Subject = "New Partner Intent registration from " + partnerModel.FullName,
                IsBodyHtml = false
            };

            // format Partner Intent Email
            sb.Append("Full name: " + partnerModel.FullName);
            sb.Append(Environment.NewLine);
            sb.Append("Email: " + partnerModel.Email);
            sb.Append(Environment.NewLine);
            sb.Append("Mailing address: " + partnerModel.MailingAddress);
            sb.Append(Environment.NewLine);
            sb.Append("City: " + partnerModel.City);
            sb.Append(Environment.NewLine);
            sb.Append("Country: " + partnerModel.Country);
            sb.Append(Environment.NewLine);
            sb.Append("Phone number: " + partnerModel.PhoneNumber);
            sb.Append(Environment.NewLine);
            sb.Append("Username: " + partnerModel.UserName);
            sb.Append(Environment.NewLine);

            msg.Body = sb.ToString();

            // send the email with Partner Intent data
            //if (EmailUtility.SendEmail(msg))
            //{
            //    msg.Dispose();
            //    ViewBag.SelectedSubverse = string.Empty;
            //    return View("~/Views/Partner/PartnerProgramIntentSent.cshtml");
            //}

            ViewBag.SelectedSubverse = string.Empty;
            return View("~/Views/Errors/Error.cshtml");
        }
    }
}

Voat/Voat.UI/Views/Partner/PartnerIntentRegistration.cshtml
@*This source file is subject to version 3 of the GPL license,
    that is bundled with this package in the file LICENSE, and is
    available online at http://www.gnu.org/licenses/gpl.txt;
    you may not use this file except in compliance with the License.

    Software distributed under the License is distributed on an "AS IS" basis,
    WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
    the specific language governing rights and limitations under the License.

    All portions of the code written by Voat are Copyright (c) 2014 Voat
    All Rights Reserved.*@

@using System.Configuration
@model Voat.Models.PartnerIntent

    @{
        ViewBag.Title = "Voat Partner Intent Registration";
    }

    <style>
        body ol {
            margin: 1em 0;
            padding: 0 0 0 40px;
        }

            body ol li {
                list-style-type: decimal;
            }

        div .centerblock {
            margin: 0 auto;
            position: relative;
            vertical-align: middle;
            width: 800px;
        }
    </style>

    <div id="container">
        <div id="about-main" class="content about-page" role="main">

            <h1>Voat Partner Intent Registration</h1>
            <br />
            <p>
                Thank you for your interest in the Voat partnership program. By filling out and submitting this form, you agree to be contacted by Voat staff in regard to Voat partnership program.
                If you have questions about this partnership program, please send us an e-mail: hello@voat.co.
            </p>
            <br /><br />
            @using (Html.BeginForm("PartnerIntentRegistration", "Partner", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary()
                @Html.HiddenFor(m => m.UserName)
                <div class="form-group">
                    @Html.LabelFor(m => m.FullName, "Full name*", new { @class = "col-md-2 control-label" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.FullName)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, "E-mail*", new { @class = "col-md-2 control-label" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.MailingAddress, "Mailing address*", new { @class = "col-md-2 control-label" })
                    <div class="col-md-5">
                        @Html.TextBoxFor(m => m.MailingAddress, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MailingAddress)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.City, "City*", new { @class = "col-md-2 control-label" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.City)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Country, "Country*", new { @class = "col-md-2 control-label" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(m => m.Country, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Country)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.PhoneNumber, "Phone number*", new { @class = "col-md-2 control-label" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PhoneNumber)
                    </div>
                </div>

                <p>Privacy notice: we will keep all personal information you entrust to us strictly confidential.</p>
                <br />

                <div class="panel panel-transparent">
                    @Html.Label("Please re-type this code", new { @class = "col-md-2 control-label" })
                    @{Html.RenderPartial("_Captcha");}
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-3">
                        <input type="submit" class="btn-whoaverse" value="Submit" />
                    </div>
                </div>
            }
            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }
        </div>
    </div>

Voat/Voat.UI/Views/Partner/PartnerProgramInformation.cshtml
@*This source file is subject to version 3 of the GPL license,
    that is bundled with this package in the file LICENSE, and is
    available online at http://www.gnu.org/licenses/gpl.txt;
    you may not use this file except in compliance with the License.

    Software distributed under the License is distributed on an "AS IS" basis,
    WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
    the specific language governing rights and limitations under the License.

    All portions of the code written by Voat are Copyright (c) 2014 Voat
    All Rights Reserved.*@

@{
    ViewBag.Title = "Voat Partner Program";
}

<div id="container">
    <div id="about-main" class="content about-page" role="main">
        <h1>What is Voat partner program?</h1>
        <p>We believe that community behind any successful service is the main reason why a service is succesful.</p>
        <p>Unfortunately, companies that run services with large communities rarely award the people that helped build said communities. In fact, they often do the opposite - they sell out and turn the community into a money-making machine with no regard for privacy of the very users that built said community.</p>
        <p>
            We plan to change all that. We want to not only give Voat company shares to our users, but we also want to try something completely new which we believe was never done before:
            <b>we want to share a fair portion of our ad revenue with the very users who share their original content, the people who write comments and the moderators who keep everything spam free</b>.
        </p>
        <h1>How will you reward users?</h1>
        <p>We are still working out the details of this process and we are open for suggestions. So far the following is being discussed:</p>
        <p>- An option to reward users with a portion of Voat ad-revenue earnings based on the quality of the content they submit to Voat</p>
        <p>- An option to let users donate their earnings to humanitarian causes</p>
        <p>- An option to let users gift their earnings to other Voat users</p>
        <h1>Why reward users?</h1>
        <p>By rewarding content creators, we hope to promote creation of original content. By rewarding people who take their time to write comments and vote, we want to encourage quality of said comments.</p>
        <h1>Won't paying users encourage spam?</h1>
        <p>On the contrary. Criteria for what the term "quality content" is still being discussed, but there will be a strict process and zero tolerance for spam. Only content which community enjoys will be subject for reward.</p>
        <h1>What about payment methods?</h1>
        <p>We plan to use digital currency for easy payments of earnings to users and content creators, but traditional payment methods will also be available.</p>
        <h1>Where do I sign up?</h1>
        We have received a sufficient amount of partnership program registrations for the initial testing stage. Registrations are now closed. Thank you for your interest in the program.
        @*<p>We thought you'd never ask! Our partnership program is still being developed, but you can <a href="/p/apply">go here to sign up</a> and express your interest in the program. We will contact you with further details once we are ready for launch.</p>*@
        <p>If you want to openly discuss our partnership program and submit your ideas or concerns, please start a new discussion in <a href="/v/announcements/comments/30925">the announcement thread</a>.</p>
    </div>
</div>

Voat/Voat.UI/Views/Partner/PartnerProgramIntentSent.cshtml
@*This source file is subject to version 3 of the GPL license,
    that is bundled with this package in the file LICENSE, and is
    available online at http://www.gnu.org/licenses/gpl.txt;
    you may not use this file except in compliance with the License.

    Software distributed under the License is distributed on an "AS IS" basis,
    WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
    the specific language governing rights and limitations under the License.

    All portions of the code written by Voat are Copyright (c) 2014 Voat
    All Rights Reserved.*@

@{
    ViewBag.Title = "Voat Partner Program";
}

<div id="container">
    <div id="about-main" class="content about-page" role="main">
        <h1>Thank you!</h1>
        <p>Thank you for expressing interest in using the Voat partner program.</p>
        <p>We will get back to you with important information when our service is ready for launch.</p>
    </div>
</div>